### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Ryan-pelo** [jerome-labidurie/d1_mini_kicad#6]
Hi, I want to use this in other open source projects. Do you want to add a license file or should I consider it licensed under the GPL or a CC license?

**Comment by jerome-labidurie** [comment]
Hello,

It's under the CC:BY-SA 3.0, you can find it in the meta/info.html documentation file.
BTW, I just added a Licence file at the root.

If you use it, please let me know. I'd like to see that.

Best regards

**Comment by Ryan-pelo** [comment]
Thank you, I hope to open source the project when I am done!
